How\ To\ Use\ DDF\ Tool.pptx: How\ To\ Use\ DDF\ Tool.md
	md2pptx How\ To\ Use\ DDF\ Tool.pptx< How\ To\ Use\ DDF\ Tool.md>> How\ To\ Use\ DDF\ Tool.log
	cat How\ To\ Use\ DDF\ Tool.log

How\ To\ Use\ DDF\ Tool.md: How\ To\ Use\ DDF\ Tool.mdp standard.css metadata.md
	mdpre -v < How\ To\ Use\ DDF\ Tool.mdp > How\ To\ Use\ DDF\ Tool.md 2> How\ To\ Use\ DDF\ Tool.log